---
url: "https://raw.githubusercontent.com/syscoin/syscoin-api/dev_2.1.3/swagger.json"
dom_id: "#swagger-ui"
validatorUrl: "https://online.swagger.io/validator"
oauth2RedirectUrl: "http://localhost:3200/oauth2-redirect.html"
